const List<String> departamentos = <String>[
  'Boaco',
  'Carazo',
  'Chinandega',
  'Chontales',
  'Estelí',
  'Granada',
  'Jinotega',
  'León',
  'Madriz',
  'Managua',
  'Masaya',
  'Matagalpa',
  'Nueva Segovia',
  'Rivas',
  'Río San Juan',
  'RAAN',
  'RAAS'
];

const Map<String, List<String>> municipios = {
  "Boaco": <String>[
    'Boaco',
    'Camoapa',
    'San José de los Remates',
    'San Lorenzo',
    'Santa Lucía',
    'Teustepe',
  ],
  "Carazo": <String>[
    "Jinotepe",
    "Diriamba",
    "Dolores",
    "El Rosario",
    "La Conquista",
    "La Paz",
    "San Marcos",
    "Santa Teresa"
  ],
  "Chinandega": <String>[
    'Chinandega',
    'Chichigalpa',
    'Corinto',
    'El Realejo',
    'El Viejo',
    'Posoltega',
    'Puerto Morazán',
    'San Francisco del Norte',
    'San Juan de Cinco Pinos',
    'San Pedro del Norte',
    'Santo Tomás del Norte',
    'Somotillo',
    'Villanueva',
  ],
  "Chontales": <String>[
    'Juigalpa',
    'Acoyapa',
    'Comalapa',
    'El Coral',
    'La Libertad',
    'San Francisco de Cuapa',
    'San Pedro de Lóvago',
    'Santo Domingo',
    'Santo Tomás',
    'Villa Sandino',
  ],
  "Estelí": <String>[
    'Estelí',
    'Condega',
    'La Trinidad',
    'Pueblo Nuevo',
    'San Juan de Limay',
    'San Nicolás',
  ],
  "Granada": <String>[
    'Granada',
    'Diriá',
    'Diriomo',
    'Nandaime',
  ],
  "Jinotega": <String>[
    'Jinotega',
    'El Cuá',
    'La Concordia',
    'San José de Bocay',
    'San Rafael del Norte',
    'San Sebastián de Yalí',
    'Santa María de Pantasma',
    'Wiwilí',
  ],
  "León": <String>[
    'León',
    'Achuapa',
    'El Jicaral',
    'El Sauce',
    'La Paz Centro',
    'Larreynaga (Malpaisillo)',
    'Nagarote',
    'Quezalguaque',
    'Santa Rosa del Peñón',
    'Telica',
  ],
  "Madriz": <String>[
    'Somoto',
    'Las Sabanas',
    'Palacagüina',
    'San José de Cusmapa',
    'San Juan de Río Coco',
    'San Lucas',
    'Telpaneca',
    'Totogalpa',
    'Yalagüina',
  ],
  "Managua": <String>[
    "Managua",
    "Ciudad Sandino",
    "El Crucero",
    "Mateare",
    "San Francisco Libre",
    "San Rafael del Sur",
    "Ticuantepe",
    "Tipitapa",
    "Villa Carlos Fonseca"
  ],
  "Masaya": <String>[
    'Masaya',
    'Catarina',
    'La Concepción',
    'Masatepe',
    'Nandasmo',
    'Nindirí',
    'Niquinohomo',
    'San Juan de Oriente',
    'Tisma',
  ],
  "Matagalpa": <String>[
    'Matagalpa',
    'Ciudad Darío',
    'El Tuma – La Dalia (Cabecera: La Dalia)',
    'Esquipulas',
    'Matiguás',
    'Muy Muy',
    'Rancho Grande',
    'Río Blanco',
    'San Dionisio',
    'San Isidro',
    'San Ramón',
    'Sébaco',
    'Terrabona',
  ],
  "Nueva Segovia": <String>[
    'Ocotal',
    'Ciudad Antigua',
    'Dipilto',
    'El Jícaro',
    'Jalapa',
    'Macuelizo',
    'Mozonte',
    'Murra',
    'Quilalí',
    'San Fernando',
    'Santa María',
    'Wiwilí',
  ],
  "Río San Juan": <String>[
    'San Carlos',
    'El Almendro',
    'El Castillo',
    'Morrito',
    'San Juan del Norte',
    'San Miguelito',
  ],
  "Rivas": <String>[
    'Rivas',
    'Altagracia',
    'Belén',
    'Buenos Aires',
    'Cárdenas',
    'Moyogalpa',
    'Potosí',
    'San Jorge',
    'San Juan del Sur',
    'Tola',
  ],
  "RAAN": <String>[
    'Puerto Cabezas',
    'Bonanza',
    'Mulukukú',
    'Prinzapolka',
    'Rosita',
    'Siuna',
    'Waslala',
    'Waspán',
  ],
  "RAAS": <String>[
    'Bluefields',
    'Corn Island',
    'Desembocadura de Río Grande',
    'El Ayote',
    'El Rama',
    'El Tortuguero',
    'Kukra Hill',
    'La Cruz de Río Grande',
    'Laguna de Perlas',
    'Muelle de los Bueyes',
    'Nueva Guinea',
    'Paiwas',
  ],
};
